apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: llm-wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 32_llm_wiki_clean_arch-frontend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Ho_Chi_Minh
        - name: NEXT_PUBLIC_API_URL
          value: /api
        - name: HOSTNAME
          value: "0.0.0.0"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
