#!/usr/bin/env python3
"""Push code quality metrics to Prometheus Pushgateway from CI.

Parses coverage.xml generated by pytest-cov and pushes code_coverage_percent
to a Pushgateway instance. Run as a CI step after pytest.

Usage:
    PUSHGATEWAY_URL=http://pushgateway:9091 python scripts/collect-quality-metrics.py
"""

import os
import sys
from xml.etree import ElementTree

import httpx


def parse_coverage(coverage_xml_path: str = "coverage.xml") -> float:
    """Extract line-rate percentage from coverage.xml."""
    if not os.path.exists(coverage_xml_path):
        print(f"Coverage file not found: {coverage_xml_path}", file=sys.stderr)
        return 0.0
    tree = ElementTree.parse(coverage_xml_path)
    root = tree.getroot()
    return float(root.attrib["line-rate"]) * 100


def push_metrics(coverage_pct: float) -> None:
    """Push code_coverage_percent metric to Pushgateway."""
    pushgateway_url = os.getenv("PUSHGATEWAY_URL")
    if not pushgateway_url:
        print("PUSHGATEWAY_URL not set, skipping metrics push")
        return

    metrics = f"code_coverage_percent {coverage_pct}\n"
    try:
        with httpx.Client() as client:
            response = client.post(
                f"{pushgateway_url.rstrip('/')}/metrics/job/code-quality/instance/ci",
                content=metrics,
                timeout=10,
            )
        if response.status_code == 200:
            print(f"Pushed coverage={coverage_pct:.1f}% to Pushgateway")
        else:
            print(f"Pushgateway returned {response.status_code}: {response.text}")
    except Exception as exc:
        print(f"Failed to push metrics: {exc}", file=sys.stderr)


if __name__ == "__main__":
    cov = parse_coverage()
    print(f"Coverage: {cov:.1f}%")
    if cov > 0:
        push_metrics(cov)
